[build]
  command = "pnpm build"
  functions = "dist"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mysql2"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index:*"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  environment = { NODE_ENV = "production" }
